name: Update Gallery

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out the repo, with full history and write‑access
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0             # fetch all history so we can commit back
          persist-credentials: true  # use the action’s token for pushes

      # 2. Set up Python (adjust version as needed)
      - name: Set up Python
        uses: actions/setup-python@v4.9.1
        with:
          python-version: '3.x'

      # 3. Run your update script
      - name: Run UpdateGallery.py
        run: python Anamnesis/Scripts/UpdateGallery.py

      # 4. Commit any changes
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          # Only commit if there are changes
          git diff --quiet || git commit -m "chore: regenerate gallery via CI"

      # 5. Push back to the repo
      - name: Push changes
        run: git push
